// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Support API",
            "email": "goliyaohugues@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authentifie l'utilisateur et retourne un token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Connexion utilisateur",
                "parameters": [
                    {
                        "description": "Identifiant et mot de passe",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ex: {user: {}, token: '...'}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Identifiants incorrects",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invalide la session (côté client). Retourne un message de confirmation.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Déconnexion",
                "responses": {
                    "200": {
                        "description": "message: Déconnexion réussie",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Crée un nouveau compte utilisateur et retourne un token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Inscription d'un utilisateur",
                "parameters": [
                    {
                        "description": "Données d'inscription",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Ex: {message: '...', user: {}, token: '...'}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Payload ou validation invalide",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/reset-password": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permet à l'utilisateur connecté de modifier son mot de passe",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Changement de mot de passe",
                "parameters": [
                    {
                        "description": "Ancien et nouveau mot de passe",
                        "name": "passwords",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.resetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: Mot de passe mis à jour",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Ancien mot de passe incorrect",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère toutes les commandes de l'utilisateur connecté avec leurs items",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Liste toutes les commandes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Utilisateur non identifié",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crée une commande, décrémente le stock et enregistre les mouvements SALE",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Créer une commande",
                "parameters": [
                    {
                        "description": "Données de la commande",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.createOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Order"
                        }
                    },
                    "400": {
                        "description": "Données invalides ou stock insuffisant",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/orders/{uuid}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère une commande par son UUID avec tous ses items",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Détails d'une commande",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de la commande",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Order"
                        }
                    },
                    "400": {
                        "description": "Format d'identifiant invalide",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Commande introuvable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Annule une commande et restaure le stock de chaque item",
                "tags": [
                    "Orders"
                ],
                "summary": "Annuler une commande",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de la commande",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Commande introuvable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère la liste des produits appartenant à l'utilisateur connecté",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Liste tous les produits",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/transport.productsResponse"
                        }
                    },
                    "401": {
                        "description": "Utilisateur non identifié",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Ajoute un nouveau produit dans la base de données",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Créer un produit",
                "parameters": [
                    {
                        "description": "Données du produit",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.productRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/transport.productRequest"
                        }
                    },
                    "400": {
                        "description": "Json ou validation invalide",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/products/{uuid}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère un produit spécifique par son UUID (doit appartenir à l'owner)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Détails d'un produit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du produit",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Product"
                        }
                    },
                    "400": {
                        "description": "Format d'identifiant invalide",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Aucun produit trouvé",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour les informations d'un produit existant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Modifier un produit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du produit",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nouvelles données",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.productRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Product"
                        }
                    },
                    "400": {
                        "description": "Données invalides",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Produit introuvable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Suppression logique d'un produit (soft delete)",
                "tags": [
                    "Products"
                ],
                "summary": "Supprimer un produit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du produit",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Echec de suppression",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Réactive un produit qui a été supprimé",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Restaurer un produit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du produit",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: Produit restauré avec succès",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Erreur lors du restore",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/shops": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère la liste des magasins de l'utilisateur",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shops"
                ],
                "summary": "Liste tous les magasins",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/transport.shopsResponse"
                        }
                    },
                    "500": {
                        "description": "Erreur de récupération",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Ajoute un nouveau magasin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shops"
                ],
                "summary": "Créer un magasin",
                "parameters": [
                    {
                        "description": "Données du magasin",
                        "name": "shop",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.shopRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Shop"
                        }
                    },
                    "400": {
                        "description": "Json Invalide",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/shops/assign-vendeur": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lier un vendeur à des magasin.\nNote: Un Admin ne peut assigner que ses propres vendeurs (parent_id doit correspondre).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shops"
                ],
                "summary": "Assigner un vendeur à des magasins",
                "parameters": [
                    {
                        "description": "IDs du vendeur et des magasins",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.AssignShopsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: Assignation réussie",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Vous n'êtes pas autorisé (Vendeur non lié à cet Admin)",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/shops/vendeur": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère tous les magasins associés au vendeur connecté (via son ID d'owner)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shops"
                ],
                "summary": "Liste les magasins d'un vendeur",
                "responses": {
                    "200": {
                        "description": "Liste des magasins avec le compte",
                        "schema": {
                            "$ref": "#/definitions/transport.shopsResponse"
                        }
                    },
                    "401": {
                        "description": "Utilisateur non identifié",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Aucun magasin trouvé",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne ou JSON invalide",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/shops/{uuid}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère un magasin spécifique par son UUID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shops"
                ],
                "summary": "Détails d'un magasin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du magasin",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Shop"
                        }
                    },
                    "400": {
                        "description": "Format d'identifiant invalide",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Aucun magasin trouvé",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour les informations d'un magasin existant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shops"
                ],
                "summary": "Modifier un magasin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du magasin",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nouvelles données",
                        "name": "shop",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.shopRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Shop"
                        }
                    },
                    "400": {
                        "description": "Données invalides",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Mise à jour impossible",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Suppression logique (soft delete) d'un magasin",
                "tags": [
                    "Shops"
                ],
                "summary": "Supprimer un magasin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du magasin",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Echec de suppression",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Réactive un magasin supprimé",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shops"
                ],
                "summary": "Restaurer un magasin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du magasin",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: Magasin restauré avec succès",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Erreur lors du restore",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/stocks": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère tous les stocks des produits de l'utilisateur connecté",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stocks"
                ],
                "summary": "Liste tous les stocks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Stock"
                            }
                        }
                    },
                    "401": {
                        "description": "Utilisateur non identifié",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/stocks/adjust": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Applique un mouvement de stock (SALE, GIFT, LOSS, ADJUSTMENT)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stocks"
                ],
                "summary": "Ajustement manuel de stock",
                "parameters": [
                    {
                        "description": "Données du mouvement",
                        "name": "stock",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.adjustStockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Données invalides ou stock insuffisant",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/stocks/detail": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère le niveau de stock d'un produit dans une boutique spécifique",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stocks"
                ],
                "summary": "Stock d'un produit dans une boutique",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID du produit",
                        "name": "product_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID de la boutique",
                        "name": "shop_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Stock"
                        }
                    },
                    "400": {
                        "description": "Paramètres invalides",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Stock introuvable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/stocks/in": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Ajoute de la quantité en stock (réception de marchandise)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stocks"
                ],
                "summary": "Entrée de stock",
                "parameters": [
                    {
                        "description": "Données d'entrée",
                        "name": "stock",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.stockInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Données invalides",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/stocks/init": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crée une entrée stock à 0 pour un produit dans une boutique",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stocks"
                ],
                "summary": "Initialiser un stock",
                "parameters": [
                    {
                        "description": "Données d'initialisation",
                        "name": "stock",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.initStockRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Données invalides",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/stocks/movements": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère l'historique complet des mouvements de l'owner",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stocks"
                ],
                "summary": "Liste tous les mouvements de stock",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StockMovement"
                            }
                        }
                    },
                    "401": {
                        "description": "Utilisateur non identifié",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/stocks/movements/product/{product_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Historique des mouvements pour un produit donné",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stocks"
                ],
                "summary": "Mouvements d'un produit",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID du produit",
                        "name": "product_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StockMovement"
                            }
                        }
                    },
                    "400": {
                        "description": "product_id invalide",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/stocks/movements/shop/{shop_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Historique des mouvements pour une boutique donnée",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stocks"
                ],
                "summary": "Mouvements d'une boutique",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la boutique",
                        "name": "shop_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.StockMovement"
                            }
                        }
                    },
                    "400": {
                        "description": "shop_id invalide",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "summary": "Liste paginée des utilisateurs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Numéro de la page (défaut: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Nombre d'éléments (défaut: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {}
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permet à un Admin ou Super Admin de créer un utilisateur.\nSi l'auteur est Admin, le rôle est forcé à 'vendeur' et lié à son ID.\nSi l'auteur est Super Admin, il peut définir le rôle.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Créer un nouvel utilisateur (Admin/Vendeur)",
                "parameters": [
                    {
                        "description": "Données de l'utilisateur à créer (email, username, password, firstname, lastname, phone)",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Ex: {message: '...', user: {models.User}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Données JSON invalides ou erreur de validation",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Accès refusé : privilèges insuffisants",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne du serveur",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{uuid}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère les détails d'un utilisateur par son UUID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Récupère un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Format d'identifiant invalide",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Aucun utilisateur trouvé",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour les informations. Seul 'super' peut changer le rôle ou le parent.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Met à jour un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update User",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/transport.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Données invalides",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Erreur de permission",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "Supprime un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "Restaure un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: Utilisateur restauré",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Category": {
            "type": "object",
            "required": [
                "category"
            ],
            "properties": {
                "category": {
                    "type": "string"
                },
                "categoryUUID": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ownerID": {
                    "type": "integer"
                }
            }
        },
        "models.Order": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OrderItem"
                    }
                },
                "orderUUID": {
                    "type": "string"
                },
                "order_id": {
                    "type": "integer"
                },
                "shop_id": {
                    "type": "integer"
                },
                "total_amount": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.OrderItem": {
            "type": "object",
            "properties": {
                "item_id": {
                    "type": "integer"
                },
                "order_id": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "unit_price": {
                    "type": "integer"
                }
            }
        },
        "models.Product": {
            "type": "object",
            "required": [
                "category",
                "productName",
                "unitPrice"
            ],
            "properties": {
                "category": {
                    "$ref": "#/definitions/models.Category"
                },
                "createdAt": {
                    "type": "string"
                },
                "ownerID": {
                    "type": "integer"
                },
                "productID": {
                    "type": "integer"
                },
                "productName": {
                    "type": "string"
                },
                "productUUID": {
                    "type": "string"
                },
                "unitPrice": {
                    "type": "integer",
                    "minimum": 0
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Shop": {
            "type": "object",
            "required": [
                "shopAddress",
                "shopMail",
                "shopName",
                "shopPhone"
            ],
            "properties": {
                "assignedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "ownerID": {
                    "type": "integer"
                },
                "shopAddress": {
                    "type": "string"
                },
                "shopID": {
                    "type": "integer"
                },
                "shopMail": {
                    "type": "string"
                },
                "shopName": {
                    "type": "string",
                    "minLength": 3
                },
                "shopPhone": {
                    "type": "string"
                },
                "shopUUID": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Stock": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "integer"
                },
                "product_name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "shop_id": {
                    "type": "integer"
                },
                "shop_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.StockMovement": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "movement_id": {
                    "type": "integer"
                },
                "movement_type": {
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "quantity_change": {
                    "type": "integer"
                },
                "shop_id": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.User": {
            "type": "object",
            "required": [
                "email",
                "firstname",
                "lastname",
                "password",
                "phone",
                "role",
                "username"
            ],
            "properties": {
                "UUID": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastname": {
                    "type": "string"
                },
                "parentID": {
                    "type": "integer"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "phone": {
                    "type": "string"
                },
                "profilePicture": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "transport.AssignShopsRequest": {
            "type": "object",
            "required": [
                "shopIDs",
                "vendeurID"
            ],
            "properties": {
                "shopIDs": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2,
                        3
                    ]
                },
                "vendeurID": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "transport.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "firstname",
                "lastname",
                "password",
                "phone",
                "role",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "jean@zoro.com"
                },
                "firstname": {
                    "type": "string",
                    "example": "Jean"
                },
                "lastname": {
                    "type": "string",
                    "example": "Dupont"
                },
                "parentId": {
                    "type": "integer"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "pass1234"
                },
                "phone": {
                    "type": "string",
                    "example": "0708091011"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "vendeur"
                    ],
                    "example": "vendeur"
                },
                "username": {
                    "type": "string",
                    "minLength": 3,
                    "example": "jean_vendeur"
                }
            }
        },
        "transport.UpdateUserRequest": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "nouveau@email.com"
                },
                "firstname": {
                    "type": "string",
                    "example": "Prince"
                },
                "lastname": {
                    "type": "string",
                    "example": "Konan"
                },
                "parentId": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string",
                    "example": "0102030405"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "vendeur"
                    ],
                    "example": "vendeur"
                },
                "username": {
                    "type": "string",
                    "example": "nouveau_pseudo"
                }
            }
        },
        "transport.adjustStockRequest": {
            "type": "object",
            "required": [
                "movement_type",
                "product_id",
                "quantity_change",
                "shop_id"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "movement_type": {
                    "type": "string",
                    "enum": [
                        "SALE",
                        "STOCK_IN",
                        "GIFT",
                        "LOSS",
                        "ADJUSTMENT"
                    ]
                },
                "product_id": {
                    "type": "integer"
                },
                "quantity_change": {
                    "type": "integer"
                },
                "shop_id": {
                    "type": "integer"
                }
            }
        },
        "transport.createOrderRequest": {
            "type": "object",
            "required": [
                "items",
                "shop_id"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/transport.orderItemRequest"
                    }
                },
                "shop_id": {
                    "type": "integer"
                }
            }
        },
        "transport.initStockRequest": {
            "type": "object",
            "required": [
                "product_id",
                "shop_id"
            ],
            "properties": {
                "product_id": {
                    "type": "integer"
                },
                "shop_id": {
                    "type": "integer"
                }
            }
        },
        "transport.loginRequest": {
            "type": "object",
            "required": [
                "identifier",
                "password"
            ],
            "properties": {
                "identifier": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "transport.orderItemRequest": {
            "type": "object",
            "required": [
                "product_id",
                "quantity"
            ],
            "properties": {
                "product_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "transport.productRequest": {
            "type": "object",
            "required": [
                "categoryID",
                "productName",
                "unitPrice"
            ],
            "properties": {
                "categoryID": {
                    "type": "integer"
                },
                "productName": {
                    "type": "string"
                },
                "unitPrice": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "transport.productsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Product"
                    }
                }
            }
        },
        "transport.resetPasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "old_password"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "minLength": 6
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "transport.shopRequest": {
            "type": "object",
            "required": [
                "shopAddress",
                "shopMail",
                "shopName",
                "shopPhone"
            ],
            "properties": {
                "shopAddress": {
                    "type": "string"
                },
                "shopMail": {
                    "type": "string"
                },
                "shopName": {
                    "type": "string",
                    "minLength": 3
                },
                "shopPhone": {
                    "type": "string"
                }
            }
        },
        "transport.shopsResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "shops": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Shop"
                    }
                }
            }
        },
        "transport.stockInRequest": {
            "type": "object",
            "required": [
                "product_id",
                "quantity",
                "shop_id"
            ],
            "properties": {
                "comment": {
                    "type": "string"
                },
                "product_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "shop_id": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" suivi d'un espace et du token JWT.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "o'z api",
	Description:      "API de gestion des utilisateurs et vendeurs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
